name: devops-cli-azenvs

volumes:
  devops-cli-azenvs-dev-home-data:
  devops-cli-azenvs-prod-home-data:

services:
  devops-cli-azenvs-dev:
    image: devops-cli-azenvs:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      AZURE_CONFIG_DIR: /config/.azure
      KUBECONFIG: /config/.kube/config
      EXTERNAL_PORT: 8782
    env_file: .dev.env
    volumes:
      - $USERPROFILE/.azure-dev:/config/.azure
      - devops-cli-azenvs-dev-home-data:/root
      - $KUBECONFIG-dev:/config/.kube/config
    ports:
      - 8782:8686
    container_name: devops-cli-azenvs-dev
    hostname: devops-cli-azenvs-dev
    stdin_open: true
    tty: true

  devops-cli-azenvs-prod:
    image: devops-cli-azenvs:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      AZURE_CONFIG_DIR: /config/.azure
      KUBECONFIG: /config/.kube/config
      EXTERNAL_PORT: 8783
    env_file: .prod.env
    volumes:
      - $USERPROFILE/.azure-prod:/config/.azure
      - devops-cli-azenvs-prod-home-data:/root
      - $KUBECONFIG-prod:/config/.kube/config
    ports:
      - 8783:8686
    container_name: devops-cli-azenvs-prod
    hostname: devops-cli-azenvs-prod
    stdin_open: true
    tty: true